/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeriodicRouteImport } from './routes/periodic'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as JaIndexRouteImport } from './routes/ja/index'
import { Route as ExamsIndexRouteImport } from './routes/exams/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as JaImportRouteImport } from './routes/ja/import'
import { Route as ExamsExamIdRouteImport } from './routes/exams/$examId'
import { Route as LearningWritingIndexRouteImport } from './routes/learning/writing/index'
import { Route as LearningVocabIndexRouteImport } from './routes/learning/vocab/index'
import { Route as LearningTextsIndexRouteImport } from './routes/learning/texts/index'
import { Route as LearningSubjectsIndexRouteImport } from './routes/learning/subjects/index'
import { Route as LearningImportIndexRouteImport } from './routes/learning/import/index'
import { Route as LearningIdiomsIndexRouteImport } from './routes/learning/idioms/index'
import { Route as LearningGrammarIndexRouteImport } from './routes/learning/grammar/index'
import { Route as LearningFlashcardsIndexRouteImport } from './routes/learning/flashcards/index'
import { Route as LearningCoursesIndexRouteImport } from './routes/learning/courses/index'
import { Route as LearningContentIndexRouteImport } from './routes/learning/content/index'
import { Route as LearningCategoriesIndexRouteImport } from './routes/learning/categories/index'
import { Route as JaVocabularyIndexRouteImport } from './routes/ja/vocabulary/index'
import { Route as JaLearnIndexRouteImport } from './routes/ja/learn/index'
import { Route as LearningWritingPracticeRouteImport } from './routes/learning/writing/practice'
import { Route as LearningFlashcardsDeckIdRouteImport } from './routes/learning/flashcards/$deckId'
import { Route as LearningCoursesIdRouteImport } from './routes/learning/courses/$id'
import { Route as LearningContentNewRouteImport } from './routes/learning/content/new'
import { Route as JaVocabularyImportRouteImport } from './routes/ja/vocabulary/import'
import { Route as JaVocabularyTermRouteImport } from './routes/ja/vocabulary/$term'
import { Route as JaTextsImportRouteImport } from './routes/ja/texts/import'
import { Route as JaIdiomsImportRouteImport } from './routes/ja/idioms/import'
import { Route as JaGrammarImportRouteImport } from './routes/ja/grammar/import'
import { Route as ExamsSessionExamIdRouteImport } from './routes/exams/session.$examId'
import { Route as ExamsResultsAttemptIdRouteImport } from './routes/exams/results/$attemptId'
import { Route as LearningFlashcardsStudyDeckIdRouteImport } from './routes/learning/flashcards/study.$deckId'
import { Route as LearningCoursesIdEditRouteImport } from './routes/learning/courses/$id.edit'
import { Route as LearningContentTypeIdRouteImport } from './routes/learning/content/$type.$id'
import { Route as JaVocabularyTermEditRouteImport } from './routes/ja/vocabulary/$term.edit'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicRoute = PeriodicRouteImport.update({
  id: '/periodic',
  path: '/periodic',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearningRoute,
} as any)
const JaIndexRoute = JaIndexRouteImport.update({
  id: '/ja/',
  path: '/ja/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamsRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const JaImportRoute = JaImportRouteImport.update({
  id: '/ja/import',
  path: '/ja/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => ExamsRoute,
} as any)
const LearningWritingIndexRoute = LearningWritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningVocabIndexRoute = LearningVocabIndexRouteImport.update({
  id: '/vocab/',
  path: '/vocab/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningTextsIndexRoute = LearningTextsIndexRouteImport.update({
  id: '/texts/',
  path: '/texts/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningSubjectsIndexRoute = LearningSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningImportIndexRoute = LearningImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningIdiomsIndexRoute = LearningIdiomsIndexRouteImport.update({
  id: '/idioms/',
  path: '/idioms/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningGrammarIndexRoute = LearningGrammarIndexRouteImport.update({
  id: '/grammar/',
  path: '/grammar/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningFlashcardsIndexRoute = LearningFlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningCoursesIndexRoute = LearningCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningContentIndexRoute = LearningContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningCategoriesIndexRoute = LearningCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => LearningRoute,
} as any)
const JaVocabularyIndexRoute = JaVocabularyIndexRouteImport.update({
  id: '/ja/vocabulary/',
  path: '/ja/vocabulary/',
  getParentRoute: () => rootRouteImport,
} as any)
const JaLearnIndexRoute = JaLearnIndexRouteImport.update({
  id: '/ja/learn/',
  path: '/ja/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningWritingPracticeRoute = LearningWritingPracticeRouteImport.update({
  id: '/writing/practice',
  path: '/writing/practice',
  getParentRoute: () => LearningRoute,
} as any)
const LearningFlashcardsDeckIdRoute =
  LearningFlashcardsDeckIdRouteImport.update({
    id: '/flashcards/$deckId',
    path: '/flashcards/$deckId',
    getParentRoute: () => LearningRoute,
  } as any)
const LearningCoursesIdRoute = LearningCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => LearningRoute,
} as any)
const LearningContentNewRoute = LearningContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => LearningRoute,
} as any)
const JaVocabularyImportRoute = JaVocabularyImportRouteImport.update({
  id: '/ja/vocabulary/import',
  path: '/ja/vocabulary/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JaVocabularyTermRoute = JaVocabularyTermRouteImport.update({
  id: '/ja/vocabulary/$term',
  path: '/ja/vocabulary/$term',
  getParentRoute: () => rootRouteImport,
} as any)
const JaTextsImportRoute = JaTextsImportRouteImport.update({
  id: '/ja/texts/import',
  path: '/ja/texts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JaIdiomsImportRoute = JaIdiomsImportRouteImport.update({
  id: '/ja/idioms/import',
  path: '/ja/idioms/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JaGrammarImportRoute = JaGrammarImportRouteImport.update({
  id: '/ja/grammar/import',
  path: '/ja/grammar/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSessionExamIdRoute = ExamsSessionExamIdRouteImport.update({
  id: '/session/$examId',
  path: '/session/$examId',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamsResultsAttemptIdRoute = ExamsResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => ExamsRoute,
} as any)
const LearningFlashcardsStudyDeckIdRoute =
  LearningFlashcardsStudyDeckIdRouteImport.update({
    id: '/flashcards/study/$deckId',
    path: '/flashcards/study/$deckId',
    getParentRoute: () => LearningRoute,
  } as any)
const LearningCoursesIdEditRoute = LearningCoursesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LearningCoursesIdRoute,
} as any)
const LearningContentTypeIdRoute = LearningContentTypeIdRouteImport.update({
  id: '/content/$type/$id',
  path: '/content/$type/$id',
  getParentRoute: () => LearningRoute,
} as any)
const JaVocabularyTermEditRoute = JaVocabularyTermEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => JaVocabularyTermRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exams': typeof ExamsRouteWithChildren
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/periodic': typeof PeriodicRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/ja/import': typeof JaImportRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/exams/': typeof ExamsIndexRoute
  '/ja/': typeof JaIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/exams/results/$attemptId': typeof ExamsResultsAttemptIdRoute
  '/exams/session/$examId': typeof ExamsSessionExamIdRoute
  '/ja/grammar/import': typeof JaGrammarImportRoute
  '/ja/idioms/import': typeof JaIdiomsImportRoute
  '/ja/texts/import': typeof JaTextsImportRoute
  '/ja/vocabulary/$term': typeof JaVocabularyTermRouteWithChildren
  '/ja/vocabulary/import': typeof JaVocabularyImportRoute
  '/learning/content/new': typeof LearningContentNewRoute
  '/learning/courses/$id': typeof LearningCoursesIdRouteWithChildren
  '/learning/flashcards/$deckId': typeof LearningFlashcardsDeckIdRoute
  '/learning/writing/practice': typeof LearningWritingPracticeRoute
  '/ja/learn/': typeof JaLearnIndexRoute
  '/ja/vocabulary/': typeof JaVocabularyIndexRoute
  '/learning/categories/': typeof LearningCategoriesIndexRoute
  '/learning/content/': typeof LearningContentIndexRoute
  '/learning/courses/': typeof LearningCoursesIndexRoute
  '/learning/flashcards/': typeof LearningFlashcardsIndexRoute
  '/learning/grammar/': typeof LearningGrammarIndexRoute
  '/learning/idioms/': typeof LearningIdiomsIndexRoute
  '/learning/import/': typeof LearningImportIndexRoute
  '/learning/subjects/': typeof LearningSubjectsIndexRoute
  '/learning/texts/': typeof LearningTextsIndexRoute
  '/learning/vocab/': typeof LearningVocabIndexRoute
  '/learning/writing/': typeof LearningWritingIndexRoute
  '/ja/vocabulary/$term/edit': typeof JaVocabularyTermEditRoute
  '/learning/content/$type/$id': typeof LearningContentTypeIdRoute
  '/learning/courses/$id/edit': typeof LearningCoursesIdEditRoute
  '/learning/flashcards/study/$deckId': typeof LearningFlashcardsStudyDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/periodic': typeof PeriodicRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/ja/import': typeof JaImportRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/exams': typeof ExamsIndexRoute
  '/ja': typeof JaIndexRoute
  '/learning': typeof LearningIndexRoute
  '/exams/results/$attemptId': typeof ExamsResultsAttemptIdRoute
  '/exams/session/$examId': typeof ExamsSessionExamIdRoute
  '/ja/grammar/import': typeof JaGrammarImportRoute
  '/ja/idioms/import': typeof JaIdiomsImportRoute
  '/ja/texts/import': typeof JaTextsImportRoute
  '/ja/vocabulary/$term': typeof JaVocabularyTermRouteWithChildren
  '/ja/vocabulary/import': typeof JaVocabularyImportRoute
  '/learning/content/new': typeof LearningContentNewRoute
  '/learning/courses/$id': typeof LearningCoursesIdRouteWithChildren
  '/learning/flashcards/$deckId': typeof LearningFlashcardsDeckIdRoute
  '/learning/writing/practice': typeof LearningWritingPracticeRoute
  '/ja/learn': typeof JaLearnIndexRoute
  '/ja/vocabulary': typeof JaVocabularyIndexRoute
  '/learning/categories': typeof LearningCategoriesIndexRoute
  '/learning/content': typeof LearningContentIndexRoute
  '/learning/courses': typeof LearningCoursesIndexRoute
  '/learning/flashcards': typeof LearningFlashcardsIndexRoute
  '/learning/grammar': typeof LearningGrammarIndexRoute
  '/learning/idioms': typeof LearningIdiomsIndexRoute
  '/learning/import': typeof LearningImportIndexRoute
  '/learning/subjects': typeof LearningSubjectsIndexRoute
  '/learning/texts': typeof LearningTextsIndexRoute
  '/learning/vocab': typeof LearningVocabIndexRoute
  '/learning/writing': typeof LearningWritingIndexRoute
  '/ja/vocabulary/$term/edit': typeof JaVocabularyTermEditRoute
  '/learning/content/$type/$id': typeof LearningContentTypeIdRoute
  '/learning/courses/$id/edit': typeof LearningCoursesIdEditRoute
  '/learning/flashcards/study/$deckId': typeof LearningFlashcardsStudyDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exams': typeof ExamsRouteWithChildren
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/periodic': typeof PeriodicRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/ja/import': typeof JaImportRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/exams/': typeof ExamsIndexRoute
  '/ja/': typeof JaIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/exams/results/$attemptId': typeof ExamsResultsAttemptIdRoute
  '/exams/session/$examId': typeof ExamsSessionExamIdRoute
  '/ja/grammar/import': typeof JaGrammarImportRoute
  '/ja/idioms/import': typeof JaIdiomsImportRoute
  '/ja/texts/import': typeof JaTextsImportRoute
  '/ja/vocabulary/$term': typeof JaVocabularyTermRouteWithChildren
  '/ja/vocabulary/import': typeof JaVocabularyImportRoute
  '/learning/content/new': typeof LearningContentNewRoute
  '/learning/courses/$id': typeof LearningCoursesIdRouteWithChildren
  '/learning/flashcards/$deckId': typeof LearningFlashcardsDeckIdRoute
  '/learning/writing/practice': typeof LearningWritingPracticeRoute
  '/ja/learn/': typeof JaLearnIndexRoute
  '/ja/vocabulary/': typeof JaVocabularyIndexRoute
  '/learning/categories/': typeof LearningCategoriesIndexRoute
  '/learning/content/': typeof LearningContentIndexRoute
  '/learning/courses/': typeof LearningCoursesIndexRoute
  '/learning/flashcards/': typeof LearningFlashcardsIndexRoute
  '/learning/grammar/': typeof LearningGrammarIndexRoute
  '/learning/idioms/': typeof LearningIdiomsIndexRoute
  '/learning/import/': typeof LearningImportIndexRoute
  '/learning/subjects/': typeof LearningSubjectsIndexRoute
  '/learning/texts/': typeof LearningTextsIndexRoute
  '/learning/vocab/': typeof LearningVocabIndexRoute
  '/learning/writing/': typeof LearningWritingIndexRoute
  '/ja/vocabulary/$term/edit': typeof JaVocabularyTermEditRoute
  '/learning/content/$type/$id': typeof LearningContentTypeIdRoute
  '/learning/courses/$id/edit': typeof LearningCoursesIdEditRoute
  '/learning/flashcards/study/$deckId': typeof LearningFlashcardsStudyDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exams'
    | '/learning'
    | '/login'
    | '/periodic'
    | '/settings'
    | '/stats'
    | '/exams/$examId'
    | '/ja/import'
    | '/oauth/callback'
    | '/exams/'
    | '/ja/'
    | '/learning/'
    | '/exams/results/$attemptId'
    | '/exams/session/$examId'
    | '/ja/grammar/import'
    | '/ja/idioms/import'
    | '/ja/texts/import'
    | '/ja/vocabulary/$term'
    | '/ja/vocabulary/import'
    | '/learning/content/new'
    | '/learning/courses/$id'
    | '/learning/flashcards/$deckId'
    | '/learning/writing/practice'
    | '/ja/learn/'
    | '/ja/vocabulary/'
    | '/learning/categories/'
    | '/learning/content/'
    | '/learning/courses/'
    | '/learning/flashcards/'
    | '/learning/grammar/'
    | '/learning/idioms/'
    | '/learning/import/'
    | '/learning/subjects/'
    | '/learning/texts/'
    | '/learning/vocab/'
    | '/learning/writing/'
    | '/ja/vocabulary/$term/edit'
    | '/learning/content/$type/$id'
    | '/learning/courses/$id/edit'
    | '/learning/flashcards/study/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/periodic'
    | '/settings'
    | '/stats'
    | '/exams/$examId'
    | '/ja/import'
    | '/oauth/callback'
    | '/exams'
    | '/ja'
    | '/learning'
    | '/exams/results/$attemptId'
    | '/exams/session/$examId'
    | '/ja/grammar/import'
    | '/ja/idioms/import'
    | '/ja/texts/import'
    | '/ja/vocabulary/$term'
    | '/ja/vocabulary/import'
    | '/learning/content/new'
    | '/learning/courses/$id'
    | '/learning/flashcards/$deckId'
    | '/learning/writing/practice'
    | '/ja/learn'
    | '/ja/vocabulary'
    | '/learning/categories'
    | '/learning/content'
    | '/learning/courses'
    | '/learning/flashcards'
    | '/learning/grammar'
    | '/learning/idioms'
    | '/learning/import'
    | '/learning/subjects'
    | '/learning/texts'
    | '/learning/vocab'
    | '/learning/writing'
    | '/ja/vocabulary/$term/edit'
    | '/learning/content/$type/$id'
    | '/learning/courses/$id/edit'
    | '/learning/flashcards/study/$deckId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exams'
    | '/learning'
    | '/login'
    | '/periodic'
    | '/settings'
    | '/stats'
    | '/exams/$examId'
    | '/ja/import'
    | '/oauth/callback'
    | '/exams/'
    | '/ja/'
    | '/learning/'
    | '/exams/results/$attemptId'
    | '/exams/session/$examId'
    | '/ja/grammar/import'
    | '/ja/idioms/import'
    | '/ja/texts/import'
    | '/ja/vocabulary/$term'
    | '/ja/vocabulary/import'
    | '/learning/content/new'
    | '/learning/courses/$id'
    | '/learning/flashcards/$deckId'
    | '/learning/writing/practice'
    | '/ja/learn/'
    | '/ja/vocabulary/'
    | '/learning/categories/'
    | '/learning/content/'
    | '/learning/courses/'
    | '/learning/flashcards/'
    | '/learning/grammar/'
    | '/learning/idioms/'
    | '/learning/import/'
    | '/learning/subjects/'
    | '/learning/texts/'
    | '/learning/vocab/'
    | '/learning/writing/'
    | '/ja/vocabulary/$term/edit'
    | '/learning/content/$type/$id'
    | '/learning/courses/$id/edit'
    | '/learning/flashcards/study/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  LearningRoute: typeof LearningRouteWithChildren
  LoginRoute: typeof LoginRoute
  PeriodicRoute: typeof PeriodicRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  JaImportRoute: typeof JaImportRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  JaIndexRoute: typeof JaIndexRoute
  JaGrammarImportRoute: typeof JaGrammarImportRoute
  JaIdiomsImportRoute: typeof JaIdiomsImportRoute
  JaTextsImportRoute: typeof JaTextsImportRoute
  JaVocabularyTermRoute: typeof JaVocabularyTermRouteWithChildren
  JaVocabularyImportRoute: typeof JaVocabularyImportRoute
  JaLearnIndexRoute: typeof JaLearnIndexRoute
  JaVocabularyIndexRoute: typeof JaVocabularyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic': {
      id: '/periodic'
      path: '/periodic'
      fullPath: '/periodic'
      preLoaderRoute: typeof PeriodicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/ja/': {
      id: '/ja/'
      path: '/ja'
      fullPath: '/ja/'
      preLoaderRoute: typeof JaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/import': {
      id: '/ja/import'
      path: '/ja/import'
      fullPath: '/ja/import'
      preLoaderRoute: typeof JaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/learning/writing/': {
      id: '/learning/writing/'
      path: '/writing'
      fullPath: '/learning/writing/'
      preLoaderRoute: typeof LearningWritingIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/vocab/': {
      id: '/learning/vocab/'
      path: '/vocab'
      fullPath: '/learning/vocab/'
      preLoaderRoute: typeof LearningVocabIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/texts/': {
      id: '/learning/texts/'
      path: '/texts'
      fullPath: '/learning/texts/'
      preLoaderRoute: typeof LearningTextsIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/subjects/': {
      id: '/learning/subjects/'
      path: '/subjects'
      fullPath: '/learning/subjects/'
      preLoaderRoute: typeof LearningSubjectsIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/import/': {
      id: '/learning/import/'
      path: '/import'
      fullPath: '/learning/import/'
      preLoaderRoute: typeof LearningImportIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/idioms/': {
      id: '/learning/idioms/'
      path: '/idioms'
      fullPath: '/learning/idioms/'
      preLoaderRoute: typeof LearningIdiomsIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/grammar/': {
      id: '/learning/grammar/'
      path: '/grammar'
      fullPath: '/learning/grammar/'
      preLoaderRoute: typeof LearningGrammarIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/flashcards/': {
      id: '/learning/flashcards/'
      path: '/flashcards'
      fullPath: '/learning/flashcards/'
      preLoaderRoute: typeof LearningFlashcardsIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/courses/': {
      id: '/learning/courses/'
      path: '/courses'
      fullPath: '/learning/courses/'
      preLoaderRoute: typeof LearningCoursesIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/content/': {
      id: '/learning/content/'
      path: '/content'
      fullPath: '/learning/content/'
      preLoaderRoute: typeof LearningContentIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/categories/': {
      id: '/learning/categories/'
      path: '/categories'
      fullPath: '/learning/categories/'
      preLoaderRoute: typeof LearningCategoriesIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/ja/vocabulary/': {
      id: '/ja/vocabulary/'
      path: '/ja/vocabulary'
      fullPath: '/ja/vocabulary/'
      preLoaderRoute: typeof JaVocabularyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/learn/': {
      id: '/ja/learn/'
      path: '/ja/learn'
      fullPath: '/ja/learn/'
      preLoaderRoute: typeof JaLearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/writing/practice': {
      id: '/learning/writing/practice'
      path: '/writing/practice'
      fullPath: '/learning/writing/practice'
      preLoaderRoute: typeof LearningWritingPracticeRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/flashcards/$deckId': {
      id: '/learning/flashcards/$deckId'
      path: '/flashcards/$deckId'
      fullPath: '/learning/flashcards/$deckId'
      preLoaderRoute: typeof LearningFlashcardsDeckIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/courses/$id': {
      id: '/learning/courses/$id'
      path: '/courses/$id'
      fullPath: '/learning/courses/$id'
      preLoaderRoute: typeof LearningCoursesIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/content/new': {
      id: '/learning/content/new'
      path: '/content/new'
      fullPath: '/learning/content/new'
      preLoaderRoute: typeof LearningContentNewRouteImport
      parentRoute: typeof LearningRoute
    }
    '/ja/vocabulary/import': {
      id: '/ja/vocabulary/import'
      path: '/ja/vocabulary/import'
      fullPath: '/ja/vocabulary/import'
      preLoaderRoute: typeof JaVocabularyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/vocabulary/$term': {
      id: '/ja/vocabulary/$term'
      path: '/ja/vocabulary/$term'
      fullPath: '/ja/vocabulary/$term'
      preLoaderRoute: typeof JaVocabularyTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/texts/import': {
      id: '/ja/texts/import'
      path: '/ja/texts/import'
      fullPath: '/ja/texts/import'
      preLoaderRoute: typeof JaTextsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/idioms/import': {
      id: '/ja/idioms/import'
      path: '/ja/idioms/import'
      fullPath: '/ja/idioms/import'
      preLoaderRoute: typeof JaIdiomsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/grammar/import': {
      id: '/ja/grammar/import'
      path: '/ja/grammar/import'
      fullPath: '/ja/grammar/import'
      preLoaderRoute: typeof JaGrammarImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/session/$examId': {
      id: '/exams/session/$examId'
      path: '/session/$examId'
      fullPath: '/exams/session/$examId'
      preLoaderRoute: typeof ExamsSessionExamIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exams/results/$attemptId': {
      id: '/exams/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/exams/results/$attemptId'
      preLoaderRoute: typeof ExamsResultsAttemptIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/learning/flashcards/study/$deckId': {
      id: '/learning/flashcards/study/$deckId'
      path: '/flashcards/study/$deckId'
      fullPath: '/learning/flashcards/study/$deckId'
      preLoaderRoute: typeof LearningFlashcardsStudyDeckIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/courses/$id/edit': {
      id: '/learning/courses/$id/edit'
      path: '/edit'
      fullPath: '/learning/courses/$id/edit'
      preLoaderRoute: typeof LearningCoursesIdEditRouteImport
      parentRoute: typeof LearningCoursesIdRoute
    }
    '/learning/content/$type/$id': {
      id: '/learning/content/$type/$id'
      path: '/content/$type/$id'
      fullPath: '/learning/content/$type/$id'
      preLoaderRoute: typeof LearningContentTypeIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/ja/vocabulary/$term/edit': {
      id: '/ja/vocabulary/$term/edit'
      path: '/edit'
      fullPath: '/ja/vocabulary/$term/edit'
      preLoaderRoute: typeof JaVocabularyTermEditRouteImport
      parentRoute: typeof JaVocabularyTermRoute
    }
  }
}

interface ExamsRouteChildren {
  ExamsExamIdRoute: typeof ExamsExamIdRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ExamsResultsAttemptIdRoute: typeof ExamsResultsAttemptIdRoute
  ExamsSessionExamIdRoute: typeof ExamsSessionExamIdRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsExamIdRoute: ExamsExamIdRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ExamsResultsAttemptIdRoute: ExamsResultsAttemptIdRoute,
  ExamsSessionExamIdRoute: ExamsSessionExamIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface LearningCoursesIdRouteChildren {
  LearningCoursesIdEditRoute: typeof LearningCoursesIdEditRoute
}

const LearningCoursesIdRouteChildren: LearningCoursesIdRouteChildren = {
  LearningCoursesIdEditRoute: LearningCoursesIdEditRoute,
}

const LearningCoursesIdRouteWithChildren =
  LearningCoursesIdRoute._addFileChildren(LearningCoursesIdRouteChildren)

interface LearningRouteChildren {
  LearningIndexRoute: typeof LearningIndexRoute
  LearningContentNewRoute: typeof LearningContentNewRoute
  LearningCoursesIdRoute: typeof LearningCoursesIdRouteWithChildren
  LearningFlashcardsDeckIdRoute: typeof LearningFlashcardsDeckIdRoute
  LearningWritingPracticeRoute: typeof LearningWritingPracticeRoute
  LearningCategoriesIndexRoute: typeof LearningCategoriesIndexRoute
  LearningContentIndexRoute: typeof LearningContentIndexRoute
  LearningCoursesIndexRoute: typeof LearningCoursesIndexRoute
  LearningFlashcardsIndexRoute: typeof LearningFlashcardsIndexRoute
  LearningGrammarIndexRoute: typeof LearningGrammarIndexRoute
  LearningIdiomsIndexRoute: typeof LearningIdiomsIndexRoute
  LearningImportIndexRoute: typeof LearningImportIndexRoute
  LearningSubjectsIndexRoute: typeof LearningSubjectsIndexRoute
  LearningTextsIndexRoute: typeof LearningTextsIndexRoute
  LearningVocabIndexRoute: typeof LearningVocabIndexRoute
  LearningWritingIndexRoute: typeof LearningWritingIndexRoute
  LearningContentTypeIdRoute: typeof LearningContentTypeIdRoute
  LearningFlashcardsStudyDeckIdRoute: typeof LearningFlashcardsStudyDeckIdRoute
}

const LearningRouteChildren: LearningRouteChildren = {
  LearningIndexRoute: LearningIndexRoute,
  LearningContentNewRoute: LearningContentNewRoute,
  LearningCoursesIdRoute: LearningCoursesIdRouteWithChildren,
  LearningFlashcardsDeckIdRoute: LearningFlashcardsDeckIdRoute,
  LearningWritingPracticeRoute: LearningWritingPracticeRoute,
  LearningCategoriesIndexRoute: LearningCategoriesIndexRoute,
  LearningContentIndexRoute: LearningContentIndexRoute,
  LearningCoursesIndexRoute: LearningCoursesIndexRoute,
  LearningFlashcardsIndexRoute: LearningFlashcardsIndexRoute,
  LearningGrammarIndexRoute: LearningGrammarIndexRoute,
  LearningIdiomsIndexRoute: LearningIdiomsIndexRoute,
  LearningImportIndexRoute: LearningImportIndexRoute,
  LearningSubjectsIndexRoute: LearningSubjectsIndexRoute,
  LearningTextsIndexRoute: LearningTextsIndexRoute,
  LearningVocabIndexRoute: LearningVocabIndexRoute,
  LearningWritingIndexRoute: LearningWritingIndexRoute,
  LearningContentTypeIdRoute: LearningContentTypeIdRoute,
  LearningFlashcardsStudyDeckIdRoute: LearningFlashcardsStudyDeckIdRoute,
}

const LearningRouteWithChildren = LearningRoute._addFileChildren(
  LearningRouteChildren,
)

interface JaVocabularyTermRouteChildren {
  JaVocabularyTermEditRoute: typeof JaVocabularyTermEditRoute
}

const JaVocabularyTermRouteChildren: JaVocabularyTermRouteChildren = {
  JaVocabularyTermEditRoute: JaVocabularyTermEditRoute,
}

const JaVocabularyTermRouteWithChildren =
  JaVocabularyTermRoute._addFileChildren(JaVocabularyTermRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExamsRoute: ExamsRouteWithChildren,
  LearningRoute: LearningRouteWithChildren,
  LoginRoute: LoginRoute,
  PeriodicRoute: PeriodicRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  JaImportRoute: JaImportRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  JaIndexRoute: JaIndexRoute,
  JaGrammarImportRoute: JaGrammarImportRoute,
  JaIdiomsImportRoute: JaIdiomsImportRoute,
  JaTextsImportRoute: JaTextsImportRoute,
  JaVocabularyTermRoute: JaVocabularyTermRouteWithChildren,
  JaVocabularyImportRoute: JaVocabularyImportRoute,
  JaLearnIndexRoute: JaLearnIndexRoute,
  JaVocabularyIndexRoute: JaVocabularyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
