/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PeriodicRouteImport } from './routes/periodic'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningTypeRouteImport } from './routes/learning'
import { Route as ExamsRouteImport } from './routes/exams'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)

const PeriodicRoute = PeriodicRouteImport.update({
  id: '/periodic',
  path: '/periodic',
  getParentRoute: () => rootRouteImport,
} as any)

const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const LearningTypeRoute = LearningTypeRouteImport.update({
  id: '/learning/$type',
  path: '/learning/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/exams': typeof ExamsRoute
  '/periodic': typeof PeriodicRoute
  '/stats': typeof StatsRoute
  '/settings': typeof SettingsRoute
  '/learning/$type': typeof LearningTypeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/exams': typeof ExamsRoute
  '/periodic': typeof PeriodicRoute
  '/stats': typeof StatsRoute
  '/settings': typeof SettingsRoute
  '/learning/$type': typeof LearningTypeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/exams': typeof ExamsRoute
  '/periodic': typeof PeriodicRoute
  '/stats': typeof StatsRoute
  '/settings': typeof SettingsRoute
  '/learning/$type': typeof LearningTypeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/exams' | '/periodic' | '/stats' | '/settings' | '/learning/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/exams' | '/periodic' | '/stats' | '/settings' | '/learning/$type'
  id: '__root__' | '/' | '/login' | '/exams' | '/periodic' | '/stats' | '/settings' | '/learning/$type'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ExamsRoute: typeof ExamsRoute
  PeriodicRoute: typeof PeriodicRoute
  StatsRoute: typeof StatsRoute
  SettingsRoute: typeof SettingsRoute
  LearningTypeRoute: typeof LearningTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic': {
      id: '/periodic'
      path: '/periodic'
      fullPath: '/periodic'
      preLoaderRoute: typeof PeriodicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$type': {
      id: '/learning/$type'
      path: '/learning/$type'
      fullPath: '/learning/$type'
      preLoaderRoute: typeof LearningTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  LoginRoute,
  ExamsRoute,
  PeriodicRoute,
  StatsRoute,
  SettingsRoute,
  LearningTypeRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
