/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeriodicRouteImport } from './routes/periodic'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningWritingIndexRouteImport } from './routes/learning/writing/index'
import { Route as LearningFlashcardsIndexRouteImport } from './routes/learning/flashcards/index'
import { Route as LearningWritingPracticeRouteImport } from './routes/learning/writing/practice'
import { Route as LearningFlashcardsDeckIdRouteImport } from './routes/learning/flashcards/$deckId'
import { Route as LearningFlashcardsStudyDeckIdRouteImport } from './routes/learning/flashcards/study.$deckId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicRoute = PeriodicRouteImport.update({
  id: '/periodic',
  path: '/periodic',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningWritingIndexRoute = LearningWritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningFlashcardsIndexRoute = LearningFlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => LearningRoute,
} as any)
const LearningWritingPracticeRoute = LearningWritingPracticeRouteImport.update({
  id: '/writing/practice',
  path: '/writing/practice',
  getParentRoute: () => LearningRoute,
} as any)
const LearningFlashcardsDeckIdRoute =
  LearningFlashcardsDeckIdRouteImport.update({
    id: '/flashcards/$deckId',
    path: '/flashcards/$deckId',
    getParentRoute: () => LearningRoute,
  } as any)
const LearningFlashcardsStudyDeckIdRoute =
  LearningFlashcardsStudyDeckIdRouteImport.update({
    id: '/flashcards/study/$deckId',
    path: '/flashcards/study/$deckId',
    getParentRoute: () => LearningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/periodic': typeof PeriodicRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/learning/flashcards/$deckId': typeof LearningFlashcardsDeckIdRoute
  '/learning/writing/practice': typeof LearningWritingPracticeRoute
  '/learning/flashcards/': typeof LearningFlashcardsIndexRoute
  '/learning/writing/': typeof LearningWritingIndexRoute
  '/learning/flashcards/study/$deckId': typeof LearningFlashcardsStudyDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/periodic': typeof PeriodicRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/learning/flashcards/$deckId': typeof LearningFlashcardsDeckIdRoute
  '/learning/writing/practice': typeof LearningWritingPracticeRoute
  '/learning/flashcards': typeof LearningFlashcardsIndexRoute
  '/learning/writing': typeof LearningWritingIndexRoute
  '/learning/flashcards/study/$deckId': typeof LearningFlashcardsStudyDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exams': typeof ExamsRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/periodic': typeof PeriodicRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/learning/flashcards/$deckId': typeof LearningFlashcardsDeckIdRoute
  '/learning/writing/practice': typeof LearningWritingPracticeRoute
  '/learning/flashcards/': typeof LearningFlashcardsIndexRoute
  '/learning/writing/': typeof LearningWritingIndexRoute
  '/learning/flashcards/study/$deckId': typeof LearningFlashcardsStudyDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exams'
    | '/learning'
    | '/login'
    | '/periodic'
    | '/settings'
    | '/stats'
    | '/learning/flashcards/$deckId'
    | '/learning/writing/practice'
    | '/learning/flashcards/'
    | '/learning/writing/'
    | '/learning/flashcards/study/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exams'
    | '/learning'
    | '/login'
    | '/periodic'
    | '/settings'
    | '/stats'
    | '/learning/flashcards/$deckId'
    | '/learning/writing/practice'
    | '/learning/flashcards'
    | '/learning/writing'
    | '/learning/flashcards/study/$deckId'
  id:
    | '__root__'
    | '/'
    | '/exams'
    | '/learning'
    | '/login'
    | '/periodic'
    | '/settings'
    | '/stats'
    | '/learning/flashcards/$deckId'
    | '/learning/writing/practice'
    | '/learning/flashcards/'
    | '/learning/writing/'
    | '/learning/flashcards/study/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamsRoute: typeof ExamsRoute
  LearningRoute: typeof LearningRouteWithChildren
  LoginRoute: typeof LoginRoute
  PeriodicRoute: typeof PeriodicRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic': {
      id: '/periodic'
      path: '/periodic'
      fullPath: '/periodic'
      preLoaderRoute: typeof PeriodicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/writing/': {
      id: '/learning/writing/'
      path: '/writing'
      fullPath: '/learning/writing/'
      preLoaderRoute: typeof LearningWritingIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/flashcards/': {
      id: '/learning/flashcards/'
      path: '/flashcards'
      fullPath: '/learning/flashcards/'
      preLoaderRoute: typeof LearningFlashcardsIndexRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/writing/practice': {
      id: '/learning/writing/practice'
      path: '/writing/practice'
      fullPath: '/learning/writing/practice'
      preLoaderRoute: typeof LearningWritingPracticeRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/flashcards/$deckId': {
      id: '/learning/flashcards/$deckId'
      path: '/flashcards/$deckId'
      fullPath: '/learning/flashcards/$deckId'
      preLoaderRoute: typeof LearningFlashcardsDeckIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/flashcards/study/$deckId': {
      id: '/learning/flashcards/study/$deckId'
      path: '/flashcards/study/$deckId'
      fullPath: '/learning/flashcards/study/$deckId'
      preLoaderRoute: typeof LearningFlashcardsStudyDeckIdRouteImport
      parentRoute: typeof LearningRoute
    }
  }
}

interface LearningRouteChildren {
  LearningFlashcardsDeckIdRoute: typeof LearningFlashcardsDeckIdRoute
  LearningWritingPracticeRoute: typeof LearningWritingPracticeRoute
  LearningFlashcardsIndexRoute: typeof LearningFlashcardsIndexRoute
  LearningWritingIndexRoute: typeof LearningWritingIndexRoute
  LearningFlashcardsStudyDeckIdRoute: typeof LearningFlashcardsStudyDeckIdRoute
}

const LearningRouteChildren: LearningRouteChildren = {
  LearningFlashcardsDeckIdRoute: LearningFlashcardsDeckIdRoute,
  LearningWritingPracticeRoute: LearningWritingPracticeRoute,
  LearningFlashcardsIndexRoute: LearningFlashcardsIndexRoute,
  LearningWritingIndexRoute: LearningWritingIndexRoute,
  LearningFlashcardsStudyDeckIdRoute: LearningFlashcardsStudyDeckIdRoute,
}

const LearningRouteWithChildren = LearningRoute._addFileChildren(
  LearningRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamsRoute: ExamsRoute,
  LearningRoute: LearningRouteWithChildren,
  LoginRoute: LoginRoute,
  PeriodicRoute: PeriodicRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
